---
title: "London fires analysis"
output: NA
---

```{r setup}
library(tidyverse)
library(gs)
library(lubridate)
```

```{r}
london_fire_incidents <- 
  read_csv("incidents.csv") %>% 
  rename(call_date = DateOfCall)

london_fire_incidents
```

```{r}
london_fire_incidents %>% 
  group_by(call_date) %>% 
  summarise(n_calls = n()) %>%
  mutate(year_call = year(call_date),
         yday_call = yday(call_date),
         day_month = make_date(year = 1970,
                               month = month(call_date), 
                               day = day(call_date))) %>%
  ggplot(aes(x = day_month, 
             y = n_calls,
             color = year_call)) +
  geom_line()
```

```{r}
on_guy_fawkes <- only_occur(in_month("Nov"), on_mday(5))
on_guy_fawkes_weekend <- only_occur(on_guy_fawkes, on_weekend())
on_christmas_day <- only_occur(in_month("Dec"), on_mday(25))
on_new_years_day <- on_yday(1)
on_us_independence_day <- only_occur(on_mday(5), in_month("Jul"))
on_halloween <- only_occur(in_month("Oct"), on_mday(31))


on_guy_fawkes
```


```{r}
london_fire_incidents %>% 
  group_by(call_date) %>% 
  summarise(n_calls = n()) %>% 
  mutate(calendar_event = case_when(
    #happen(on_guy_fawkes_weekend, call_date) ~ "Guy Fawkes weekend",
    happen(on_guy_fawkes, call_date) ~ "Guy Fawkes",
    happen(on_halloween, call_date) ~ "Halloween",
    happen(on_christmas_day, call_date) ~ "Christmas Day",
    happen(on_new_years_day, call_date) ~ "New Year's Day",
    happen(on_easter_weekend(), call_date) ~ "Easter Weekend",
    happen(on_us_independence_day, call_date) ~ "US Independence Day",
    #happen(on_weekend(), call_date) ~ "Weekend",
    #happen(on_weekday(), call_date) ~ "Weekday",
    TRUE ~ "Normal day"
  )) %>% 
  mutate(on_weekend = if_else(happen(on_weekend(), call_date), "Weekend", "Weekday")) %>% 
  group_by(calendar_event, on_weekend) %>% 
  summarise(mean_calls = mean(n_calls)) %>%
  ungroup() %>% 
  mutate(calendar_event = fct_reorder(calendar_event, mean_calls, mean)) %>% 
  group_by(on_weekend) %>% 
  #mutate(mean_day_type = mean(mean_calls)) %>% 
  mutate(mean_day_type = mean_calls[calendar_event == "Normal day"]) %>% 
  ungroup() %>% 
  mutate(diff_from_mean = mean_calls - mean_day_type) %>% 
  ggplot(aes(x = calendar_event, 
             fill = on_weekend,
             y = diff_from_mean)) +
  geom_col(position = position_dodge()) +
  coord_flip() #+
  #facet_grid(. ~ on_weekend)
```

